/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logger.h"

bool_t
xdr_log_args (XDR *xdrs, log_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 64))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, 256))
		 return FALSE;
	return TRUE;
}
