/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGGER_H_RPCGEN
#define _LOGGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NAME_LEN 256
#define MAX_OP_LEN 64
#define MAX_FILE_LEN 256

struct log_args {
	char *username;
	char *operation;
	char *filename;
};
typedef struct log_args log_args;

#define LOGGER_PROG 0x20001234
#define LOGGER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERATION 1
extern  int * log_operation_1(log_args *, CLIENT *);
extern  int * log_operation_1_svc(log_args *, struct svc_req *);
extern int logger_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERATION 1
extern  int * log_operation_1();
extern  int * log_operation_1_svc();
extern int logger_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_args (XDR *, log_args*);

#else /* K&R C */
extern bool_t xdr_log_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGGER_H_RPCGEN */
